In [2]:
import jax.numpy as jnp

In [5]:
pose_1 = jnp.load('data/pose_1.npz')
pose_2 = jnp.load('data/pose_2.npz')
pose_3 = jnp.load('data/pose_3.npz')
pose_4 = jnp.load('data/pose_4.npz')
poses = [pose_1, pose_2, pose_3, pose_4]
pose_1.files

['joints',
 'geo_vals',
 'rot_errors',
 'pos_errors',
 'mass_vals',
 'jac_vals',
 'qdot_vals',
 'grav_vals',
 'pose_vals',
 'cart_vel_val',
 'momenta']

In [10]:
poses[0]['pose_vals'][0]

array([[-0.6325    , -0.47329998, -0.6132    , -0.1566    ],
       [-0.24949999,  0.8739    , -0.4172    ,  0.4886    ],
       [ 0.7333    , -0.1108    , -0.6708    ,  0.3385    ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]],
      dtype=float32)

In [12]:
poses[1]['pose_vals'][0]

array([[ 0.0483    , -0.816     , -0.576     , -0.0721    ],
       [-0.8538    ,  0.26549998, -0.44779998,  0.5427    ],
       [ 0.5184    ,  0.51339996, -0.6839    ,  0.1549    ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]],
      dtype=float32)

In [14]:
poses[2]['pose_vals'][0]

array([[-0.1829    , -0.6221    , -0.76129997, -0.09999999],
       [-0.97789997,  0.195     ,  0.0756    ,  0.34289998],
       [ 0.1014    ,  0.7583    , -0.644     ,  0.3101    ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]],
      dtype=float32)

In [16]:
poses[3]['pose_vals'][0]

array([[ 0.2844    ,  0.2483    , -0.926     , -0.0464    ],
       [ 0.65209997,  0.6579    ,  0.37669998,  0.2067    ],
       [ 0.7028    , -0.71099997,  0.0252    ,  0.0662    ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]],
      dtype=float32)

In [20]:
target_pose = jnp.load('data/target_square_hole.npz')
target_pose['pose']

array([[ 0.012     ,  0.0734    , -0.99719995, -0.2701    ],
       [ 0.014     ,  0.99719995,  0.0735    ,  0.3125    ],
       [ 0.99979997, -0.0149    ,  0.011     ,  0.0387    ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]],
      dtype=float32)